version: 2.1
executors:
  build-executor:
    working_directory: /workspace
    docker:
      - image: microsoft/dotnet:2.1-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  test:
    executor: build-executor
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test /workspace/test/DaedalusCompiler.Tests/DaedalusCompiler.Tests.csproj
  build-release:
    executor: build-executor
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet publish -c Release
      - persist_to_workspace:
          root: /workspace/src/DaedalusCompiler/bin/Release/netcoreapp2.1
          paths:
            - publish
  publish-github-release:
    docker:
    - image: circleci/golang:1.8
    steps:
    - attach_workspace:
        at: ./compiler-build
    - run: pwd
    - run: ls compiler-build/publish
    - run: mkdir artifacts
    - run: touch artifacts/program.exe && echo "hello" >> artifacts/program.exe && chmod 777 artifacts/program.exe
    - run:
        name: "Publish Release on GitHub"
        command: |
          go get github.com/tcnksm/ghr
          VERSION=v0.0.1
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  main:
    jobs:
    - build-release
    - publish-github-release:
        requires:
          - build-release